spring:
  application:
    name: spring-starter
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Coutinho2603
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8300
  servlet:
    context-path: /api/saving
